# Generated by Django 5.2.7 on 2025-10-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qapair",
            name="answer",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="qapair",
            name="question",
            field=models.CharField(max_length=255),
        ),
    ]
